// Auto-generated by scripts/generate-config.sh
// Do not commit this file.
window.APP_CONFIG = {
  endpoint: "https://cloud.appwrite.io/v1",
  projectId: "69c42483003946131583",
  bucketId: "69c43407001879887c6c",
  databaseId: "69c43838001f909d31c3",
  collectionId: "images"
};
