#!/usr/bin/env bash
set -euo pipefail

# This script converts environment variables into runtime-config.js,
# which the browser can read via window.APP_CONFIG.
#
# Why this exists:
# - Browser JavaScript cannot directly read .env files.
# - We keep .env private and generate a runtime config file instead.

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${1:-$ROOT_DIR/.env}"
OUT_FILE="$ROOT_DIR/runtime-config.js"

# Load .env if present (local dev). In CI/Appwrite builds, variables can be
# provided directly via environment settings, so missing .env is acceptable.
if [[ -f "$ENV_FILE" ]]; then
  set -a
  source "$ENV_FILE"
  set +a
  SOURCE_DESC="$ENV_FILE"
else
  SOURCE_DESC="process environment"
fi

# Appwrite Sites automatically provides these variables.
# Use them as fallback when custom APPWRITE_* vars are not explicitly set.
: "${APPWRITE_ENDPOINT:=${APPWRITE_SITE_API_ENDPOINT:-}}"
: "${APPWRITE_PROJECT_ID:=${APPWRITE_SITE_PROJECT_ID:-}}"

required_vars=(
  APPWRITE_ENDPOINT
  APPWRITE_PROJECT_ID
  APPWRITE_BUCKET_ID
  APPWRITE_DATABASE_ID
  APPWRITE_COLLECTION_ID
)

for var in "${required_vars[@]}"; do
  if [[ -z "${!var:-}" ]]; then
    echo "Error: missing required variable '$var' in $SOURCE_DESC" >&2
    exit 1
  fi
done

cat > "$OUT_FILE" <<EOF
// Auto-generated by scripts/generate-config.sh
// Do not commit this file.
window.APP_CONFIG = {
  endpoint: "${APPWRITE_ENDPOINT}",
  projectId: "${APPWRITE_PROJECT_ID}",
  bucketId: "${APPWRITE_BUCKET_ID}",
  databaseId: "${APPWRITE_DATABASE_ID}",
  collectionId: "${APPWRITE_COLLECTION_ID}",
  studentPagesCollectionId: "${APPWRITE_STUDENT_PAGES_COLLECTION_ID:-}",
  studentsTeamId: "${APPWRITE_STUDENTS_TEAM_ID:-}"
};
EOF

echo "Generated $OUT_FILE from $SOURCE_DESC"
